services:
  db:
    image: mysql:8.0
    container_name: mysql_hub_educacional
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hub_educacional
      MYSQL_USER: hub_user
      MYSQL_PASSWORD: hub_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: